/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myapplication9_MainActivity */

#ifndef _Included_com_example_administrator_myapplication9_MainActivity
#define _Included_com_example_administrator_myapplication9_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_administrator_myapplication9_MainActivity_REQUEST_TAKE_PHOTO
#define com_example_administrator_myapplication9_MainActivity_REQUEST_TAKE_PHOTO 0L
#undef com_example_administrator_myapplication9_MainActivity_REQUEST_TAKE_PHOTO1
#define com_example_administrator_myapplication9_MainActivity_REQUEST_TAKE_PHOTO1 1L
#ifdef __cplusplus
}
#endif
#endif
